### ISSUE TITLE
instalation Problem ...

### ISSUE THREAD

**Issue by senkron24** [xtreamui/XtreamUI#109]
end of teh instaltion i get this no way to pass it pls help ..

Traceback (most recent call last):
  File "install.py", line 193, in <module>
    if not mysql(rUsername, rPassword): sys.exit(1)
  File "install.py", line 93, in mysql
    rFile = open("/etc/mysql/my.cnf", "w")
IOError: [Errno 13] Permission denied: '/etc/mysql/my.cnf'

**Comment by sam43434** [comment]
is this fresh install?

**Comment by senkron24** [comment]
no its not fresh it was installed xtream befor :(( i wold be reinstalled xtream becouse the streams opened very late 
for exampel opened stream 7 second ondeamond 15 second i hope the reinstalation will help slove this problem..
